<script>
  import flowImg from '../assets/deliberation-flow.svg'
</script>

<h2 style="font-size: 1.7rem; margin-bottom: 0.15em;">Deliberation: one scored intention per tick</h2>
<p class="subtitle" style="font-size: 0.92rem; margin-top: 0.2em;">
  <span class="mono">getBestIntention()</span> reduces the whole belief store to a single best action. For the solo BDI it is pure utility math — no rules, no LLM.
</p>

<div class="delib-grid">
  <!-- 1. DIAGRAM: the decision spine (generated by scripts/deliberation_diagram.py) -->
  <div class="diagram-panel">
    <span class="panel-tag mono">getBestIntention()</span>
    <img class="flow-img" src={flowImg} alt="getBestIntention decision flow: position known, carrying, same-tile pickup, best scored pickup, else explore" />
  </div>

  <!-- right column: the three reasoning pieces -->
  <div class="detail-col">
    <!-- 2. SCORING, PICKUP, CARRYING -->
    <div class="card blue-border">
      <h3>Scoring, pickup &amp; carrying</h3>
      <ul>
        <li>Score = <strong>reward at delivery − path steps</strong>, not raw reward: <span class="mono">estimatedRewardAtDelivery − totalSteps</span></li>
        <li>Steps use the <strong>real A* path</strong> (me&#8594;parcel&#8594;delivery); reward decays over the trip via learned <span class="mono">MS_PER_STEP</span></li>
        <li>Best free parcel wins, <span class="mono">0</span>-at-delivery rejected; carrying &#8594; best delivery tile, stop detouring at full <span class="mono">MAX_PARCELS</span></li>
      </ul>
    </div>

    <!-- 3. DETOUR REWARD + CACHE -->
    <div class="card orange-border">
      <h3>Reward for deviation &amp; detour cache</h3>
      <ul>
        <li><span class="mono">detourValue</span> = reward of grabbing one more − reward of delivering now (carried parcels keep decaying)</li>
        <li>Pay for the route: <span class="mono">effectiveGain = gain − extraSteps</span>. Accept <span class="mono">≤ 3 &amp; gain &gt; 0</span>, or <span class="mono">≤ 8 &amp; effectiveGain ≥ 10</span></li>
        <li><strong>Detour cache</strong> per parcel, tied to the current tile, cleared on move; caches <span class="mono">null</span> legs too — dead routes are costly to recheck</li>
      </ul>
    </div>

    <!-- 4. EXPLORATION -->
    <div class="card purple-border">
      <h3>Exploration</h3>
      <ul>
        <li>No parcel worth taking &#8594; roam toward spawners</li>
        <li><strong>Frequent spawns:</strong> camp the nearest spawner. <strong>Sparse / rare</strong> (≥ <span class="mono">5s</span> or out of view): patrol in stable order, dwell <span class="mono">300ms</span>, persistent index</li>
        <li>Always opportunistic — grab a parcel ≤ <span class="mono">3</span> tiles even while parked</li>
      </ul>
    </div>
  </div>
</div>


<style>
  .delib-grid {
    display: grid;
    grid-template-columns: minmax(300px, 400px) minmax(420px, 1fr);
    gap: 24px;
    width: 100%;
    max-width: 1080px;
    margin-top: 10px;
    align-items: center;
  }

  /* diagram panel */
  .diagram-panel {
    position: relative;
    display: flex;
    justify-content: center;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 22px 14px 12px;
  }
  .panel-tag {
    position: absolute;
    top: -10px;
    left: 16px;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 2px 8px;
    font-size: 0.72rem;
    color: var(--text-muted);
  }
  .flow-img {
    display: block;
    max-width: 100%;
    max-height: 58vh;
    width: auto;
    height: auto;
    margin: 0 auto;
  }

  /* right column cards */
  .detail-col { display: flex; flex-direction: column; gap: 10px; }
  /* override global `.card { flex: 1 1 300px }` — in a column that becomes a 300px height basis */
  .detail-col .card { flex: 0 0 auto; padding: 11px 16px; }
  .detail-col h3 { margin-bottom: 4px; font-size: 1.08rem; }
  .detail-col ul { margin: 0; padding-left: 17px; }
  .detail-col li {
    text-align: left;
    color: var(--text-muted);
    font-size: 0.92rem;
    line-height: 1.45;
    margin-bottom: 4px;
  }
  .detail-col li strong { color: var(--heading); }

  @media (max-width: 860px) {
    .delib-grid { grid-template-columns: 1fr; }
  }
</style>
