<script>
  import loopImg from '../assets/executor-loop.svg'
  import stepImg from '../assets/executor-step.svg'
</script>

<h2 style="font-size: 1.7rem; margin-bottom: 0.15em;">Executor: one socket action per tick</h2>
<p class="subtitle" style="font-size: 0.92rem; margin-top: 0.2em;">
  A polling loop — guards gate each tick, then a single move (or conflict resolution) fires.
</p>

<div class="exec-grid">
  <!-- 1. LOOP: the per-tick guard gauntlet (generated by scripts/executor_diagram.py) -->
  <div class="diagram-panel">
    <span class="panel-tag mono">startExecutor() loop</span>
    <img class="flow-img" src={loopImg} alt="Executor tick loop: socket, position, pause, yield, intention guards, then dispatch, looping back each tick" />
  </div>

  <!-- 2. STEP: stepTowardsTarget move-or-resolve ladder -->
  <div class="diagram-panel">
    <span class="panel-tag mono">stepTowardsTarget()</span>
    <img class="flow-img" src={stepImg} alt="stepTowardsTarget ladder: at target finalize, plan, validity, emit move, and the conflict ladder on a blocked move" />
  </div>
</div>

<div class="detail-row">
  <div class="card blue-border">
    <h3>Guards &amp; dispatch</h3>
    <ul>
      <li>Each tick early-exits on <strong>transport down, unknown position, or peer pause</strong> — then loops</li>
      <li>A new intention is <span class="mono">active</span> + broadcast; type routes to <span class="mono">stepTowardsTarget</span> or <span class="mono">runHandoff</span></li>
    </ul>
  </div>
  <div class="card green-border">
    <h3>Plan &amp; finalize</h3>
    <ul>
      <li>Plan built on demand (A* / PDDL); <span class="mono">isStepValid</span> re-checks before every step, else clear &amp; replan</li>
      <li>At target &#8594; <span class="mono">emitPickup</span> / <span class="mono">emitPutdown</span>, update beliefs, <span class="mono">notifyIntentionDone</span></li>
    </ul>
  </div>
  <div class="card orange-border">
    <h3>Conflict ladder</h3>
    <ul>
      <li>Teammate carrying more &#8594; <strong>right-of-way</strong> retreat or wait</li>
      <li>3 fails on a non-critical tile &#8594; <span class="mono">5s</span> blacklist + backoff &#8594; <span class="mono">notifyActionFailed</span></li>
    </ul>
  </div>
</div>

<style>
  .exec-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 24px;
    width: 100%;
    max-width: 1160px;
    margin: 8px auto 0;
    align-items: stretch;
  }

  .diagram-panel {
    position: relative;
    display: flex;
    justify-content: center;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 22px 14px 12px;
  }
  .panel-tag {
    position: absolute;
    top: -10px;
    left: 16px;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 2px 8px;
    font-size: 0.72rem;
    color: var(--text-muted);
  }
  .flow-img {
    display: block;
    max-width: 100%;
    max-height: 46vh;
    width: 100%;
    height: auto;
    margin: 0 auto;
  }

  .detail-row {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 12px;
    width: 100%;
    max-width: 1160px;
    margin: 12px auto 0;
  }
  .detail-row .card { flex: 0 0 auto; padding: 10px 15px; }
  .detail-row h3 { margin-bottom: 4px; font-size: 1.02rem; }
  .detail-row ul { margin: 0; padding-left: 16px; }
  .detail-row li {
    text-align: left;
    color: var(--text-muted);
    font-size: 0.86rem;
    line-height: 1.4;
    margin-bottom: 4px;
  }
  .detail-row li strong { color: var(--heading); }

  @media (max-width: 900px) {
    .exec-grid { grid-template-columns: 1fr; }
    .detail-row { grid-template-columns: 1fr; }
  }
</style>
