<script>
  import flowImg from '../assets/pddl-flow.svg'
</script>

<h2 style="font-size: 1.7rem; margin-bottom: 0.15em;">PDDL mode: planning <em>through</em> obstacles</h2>
<p class="subtitle" style="font-size: 0.92rem; margin-top: 0.2em;">
  Same BDI loop — A* is swapped for a symbolic solver run as a service. Each intention regenerates a PDDL problem from current beliefs.
</p>

<!-- DIAGRAM: the planWithPDDL() two-phase pipeline (generated by scripts/pddl_diagram.py) -->
<div class="diagram-panel">
  <span class="panel-tag mono">planWithPDDL()</span>
  <img class="flow-img" src={flowImg} alt="PDDL two-phase solve: intention rebuilds a PDDL problem, Phase 1 plans with crates as walls, and only if no free route exists does Phase 2 enable crate pushing; the result is a move list or no_path" />
</div>

<div class="cols">
  <div class="card blue-border">
    <h3>Dynamic agents excluded &amp; timeout</h3>
    <ul>
        <li>Visible agents are treated as <strong>blocked tiles</strong> (removed from the tile set); the solver does not model their future movement</li>
        <li>Solver interrupted after <span class="mono">5s</span>; on failure the executor reports <span class="mono">no_path</span> and revision picks a new intention</li>
    </ul>
  </div>
  <div class="card green-border">
    <h3>Domain</h3>
    <ul>
      <li>Navigation (<span class="mono">move-right/left/up/down</span>), pickup and delivery</li>
      <li>Crate pushing (<span class="mono">push-right/left/up/down</span>) — crates can be pushed <strong>only</strong> onto <span class="mono">crate-slot</span> tiles (type 5)</li>
    </ul>
  </div>
</div>

<div class="cols">
  <div class="card orange-border">
    <h3>Two-phase strategy</h3>
    <ul>
      <li>Plan first with <strong>no pushing</strong> (crates = walls); enable pushing only if no free path exists</li>
      <li>Avoids needless pushes that clutter the map</li>
    </ul>
  </div>
  <div class="card purple-border">
    <h3>Directional tiles</h3>
    <ul>
      <li>Arrow-tile crossing constraints are encoded as facts <span class="mono">(right/left/up/down from to)</span></li>
      <li>The planner respects the allowed directions automatically</li>
    </ul>
  </div>
</div>

<style>
  /* diagram panel (mirrors the Deliberation slide) */
  .diagram-panel {
    position: relative;
    display: flex;
    justify-content: center;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 20px 14px 10px;
    margin: 14px 0 4px;
  }
  .panel-tag {
    position: absolute;
    top: -10px;
    left: 16px;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 2px 8px;
    font-size: 0.72rem;
    color: var(--text-muted);
  }
  .flow-img {
    display: block;
    max-width: 100%;
    max-height: 34vh;
    width: auto;
    height: auto;
    margin: 0 auto;
  }
</style>
